    
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1213love
    url: jdbc:mysql://localhost/SpringCloud_Sell?charsetEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev2
girl:
  name: huhu
  age: 1
